// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiAK7DlbgSyW4lIOoz0xdISoFvVrrFGj0',
    appId: '1:595857123883:web:04a5687808ce5d3a1bd86e',
    messagingSenderId: '595857123883',
    projectId: 'twitterclone-9471d',
    authDomain: 'twitterclone-9471d.firebaseapp.com',
    storageBucket: 'twitterclone-9471d.firebasestorage.app',
    measurementId: 'G-EF0JR1MKFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB665GqwtbSBSFmJK2bOC7WgUo9-KmgvK0',
    appId: '1:595857123883:android:b91368abfc954a801bd86e',
    messagingSenderId: '595857123883',
    projectId: 'twitterclone-9471d',
    storageBucket: 'twitterclone-9471d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjrPdgBmOzZSaNYaEWc90d3EIHMCJUJNU',
    appId: '1:595857123883:ios:d7834ed46b42f3911bd86e',
    messagingSenderId: '595857123883',
    projectId: 'twitterclone-9471d',
    storageBucket: 'twitterclone-9471d.firebasestorage.app',
    iosClientId: '595857123883-eck0tchgqpfnpt32l8cv1n3pt3ffpakf.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjrPdgBmOzZSaNYaEWc90d3EIHMCJUJNU',
    appId: '1:595857123883:ios:d7834ed46b42f3911bd86e',
    messagingSenderId: '595857123883',
    projectId: 'twitterclone-9471d',
    storageBucket: 'twitterclone-9471d.firebasestorage.app',
    iosClientId: '595857123883-eck0tchgqpfnpt32l8cv1n3pt3ffpakf.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiAK7DlbgSyW4lIOoz0xdISoFvVrrFGj0',
    appId: '1:595857123883:web:a5ac07fbba5d51b31bd86e',
    messagingSenderId: '595857123883',
    projectId: 'twitterclone-9471d',
    authDomain: 'twitterclone-9471d.firebaseapp.com',
    storageBucket: 'twitterclone-9471d.firebasestorage.app',
    measurementId: 'G-WXJL8KX1K6',
  );
}
